title: Robot Clasificador de Residuos
description: Documentación del proyecto final de Sistemas Ciberfísicos sobre un robot que recolecta y clasifica materiales reciclables.
theme: just-the-docs
url: https://sebas30073007.github.io/Sistemas_Ciberfisicos_Proyecto/
aux_links:
  Bitácora del proyecto: https://sebas30073007.github.io/Sistemas_Ciberfisicos_Proyecto/
nav_sort: case_sensitive
lang: es
